### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by saxenanamay**
Corrected a typo in the README.md (implimented->implemented)

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
This is so trivial that I am just going to correct it myself.

**Comment by saxenanamay** [comment]
new to github, still figuring things out..

**Comment by MasterOfTheTiger** [comment]
That's okay. ;)

You here for hacktoberfest?

**Comment by saxenanamay** [comment]
That's what got me into it, yes, but I want to make more contributions..

**Comment by MasterOfTheTiger** [comment]
@saxenanamay what technologies are you good at?

**Comment by saxenanamay** [comment]
Wouldn't say good but I've got some experience with C, C++, PHP, node.js,
express.js, mysql and mongodb. Learning react as of now..

**Comment by MasterOfTheTiger** [comment]
@saxenanamay That is good. I have experience in a couple of those. Are you interested in helping out with the PHP version of Heb12?

**Comment by saxenanamay** [comment]
Sure!

**Comment by MasterOfTheTiger** [comment]
@saxenanamay You can see what I have done already here: https://github.com/heb12/heb12web

**Comment by MasterOfTheTiger** [comment]
Very odd. It works for me. And it is a public repo.... What happens when you try it?

**Comment by saxenanamay** [comment]
Dw I cloned it like 2 hours ago. It wasnt working before though. Perhaps
there was an issue with github earlier?

**Comment by MasterOfTheTiger** [comment]
Possibly. Well I just pushed some changes to the license. You should pull from origin again. Looking at the code, do you think you can help out?

**Comment by saxenanamay** [comment]
I'm really not sure what I'm supposed to do. I'll look around and try make
it a bit more like the electron app.

**Comment by MasterOfTheTiger** [comment]
Well. That is not exactly the goal. It would be better if it was more like something like BibleGateway. Anyway, the main thing that needs to be worked on is making a PHP version of openbibles. Https://gitlab.com/masterofthetiger/openbibles

**Pull request closed without merging**
